image:
  repository: localhost:5005/checkout
  tag: latest
  pullPolicy: IfNotPresent

gateway:
  enabled: true

networkPolicy:
  enabled: true

rabbitmq:
  enabled: false

postgresql:
  enabled: false
