{{- if .Values.ingressroute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "chart-libs.fullname" . }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressroute.entryPoints | nindent 4 }}
  routes:
    {{- range $route := .Values.ingressroute.routes }}
    - match: Host(`{{ $.Values.ingressroute.host }}`) && PathPrefix(`{{ $route.path }}`)
      kind: Rule
      services:
        - name: {{ $route.service.name }}
          port: {{ $route.service.port }}
      {{- if $route.middlewares }}
      middlewares:
        {{- range $middleware := $route.middlewares }}
        - name: {{ include "chart-libs.fullname" $ }}-{{ $middleware.name }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
