image:
  repository: localhost:5005/ecommerce
  tag: latest

service:
  type: ClusterIP

resources:
  #limits:
  #  cpu: 200m
  #  memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

applicationYaml:
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://keycloak.tools.svc.cluster.local/realms/labs64io
    rabbitmq:
      host: rabbitmq.tools.svc.cluster.local
      port: 5672
      username: labs64
      password: labs64pw
