image:
  repository: localhost:5005/ecommerce
  tag: latest

service:
  type: ClusterIP

resources:
  #limits:
  #  cpu: 200m
  #  memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

applicationYaml:
  spring:
    rabbitmq:
      host: rabbitmq.tools.svc.cluster.local
      port: 5672
      username: labs64
      password: labs64pw

  data:
    redis:
      host: redis-master.tools.svc.cluster.local
      port: 6379
      timeout: 60000
      username: labs64
      password: labs64pw
      database: 0

cart:
  ttl-hours: 6