image:
  tag: 13.1.0

service:
  type: LoadBalancer
  port: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
      - name: Loki
        orgId: 1
      - name: Tempo
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: Prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        uid: Loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
      - name: Tempo
        type: tempo
        uid: Tempo
        url: http://tempo.monitoring.svc.cluster.local:3200
        access: proxy

plugins: []

# Enable persistence for Grafana dashboards and configurations
persistence:
  enabled: true
  type: pvc
  size: 10Gi
  accessModes:
    - ReadWriteOnce

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: "ALL"
    enableUniqueFilenames: true
    env:
      - name: ENABLE_UNIQUE_FILENAMES
        value: "true"
initChownData:
  enabled: false
grafana.ini:
  server:
    domain: gateway.localhost
    root_url: "%(protocol)s://%(domain)s/grafana/"
    serve_from_sub_path: true
