# -- Pipeline configuration
pipelineConfig:
  enabled: true
  config:
    otel-trace-pipeline:
      delay: 100
      source:
        otel_trace_source:
          ssl: false
      buffer:
        bounded_blocking:
          buffer_size: 1024
          batch_size: 256
      sink:
        - pipeline:
            name: "raw-trace-pipeline"
        - pipeline:
            name: "service-map-pipeline"
    raw-trace-pipeline:
      source:
        pipeline:
          name: "otel-trace-pipeline"
      buffer:
        bounded_blocking:
          buffer_size: 1024
          batch_size: 256
      processor:
        - otel_traces:
      sink:
        - opensearch:
            hosts: ["https://opensearch-cluster-master.tools.svc.cluster.local:9200"]
            insecure: true
            # https://docs.opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/opensearch/#opensearch-cluster-security
            username: admin
            password: "Labs64pw+"
            index_type: trace-analytics-raw
            connection_timeout: 30000
            socket_timeout: 60000
            max_retries: 10
    service-map-pipeline:
      delay: 100
      source:
        pipeline:
          name: "otel-trace-pipeline"
      buffer:
        bounded_blocking:
          buffer_size: 1024
          batch_size: 256
      processor:
        - service_map:
      sink:
        - opensearch:
            hosts: ["https://opensearch-cluster-master.tools.svc.cluster.local:9200"]
            insecure: true
            # https://docs.opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/opensearch/#opensearch-cluster-security
            username: admin
            password: "Labs64pw+"
            index_type: trace-analytics-service-map
            connection_timeout: 30000
            socket_timeout: 60000
            max_retries: 10

# -- Data Prepper ports
ports:
  # -- The port that the source is running on. Default value is 2021. Valid options are between 0 and 65535.
  # https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/http-source/
  - name: http-source
    port: 2021
  # -- The port that the otel_trace_source source runs on. Default value is 21890.
  # https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/otel-trace-source/
  - name: otel-traces
    port: 21890
  # -- The port that the OpenTelemtry metrics source runs on. Default value is 21891.
  # https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/otel-metrics-source/
  - name: otel-metrics
    port: 21891
  # -- Represents the port that the otel_logs_source source is running on. Default value is 21892.
  # https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/otel-logs-source/
  - name: otel-logs
    port: 21892
