image:
  repository: payment-gateway
  tag: latest
  pullPolicy: IfNotPresent

gateway:
  enabled: true

networkPolicy:
  enabled: true

rabbitmq:
  enabled: true

postgresql:
  enabled: true

redis:
  enabled: true
