apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-libs.fullname" . }}-pipelines
  labels:
    {{- include "chart-libs.labels" . | nindent 4 }}
data:
  pipelines.yaml: |-
    auditflow:
{{ toYaml .Values.application.auditflow | indent 6 }}