prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

grafana:
  enabled: false # Deploy a separate Grafana instance

alertmanager:
  enabled: false # Optional, can be enabled if you need alerting

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
