image:
  repository: localhost:5005/api-gateway
  tag: latest

service:
  type: ClusterIP

resources:
  #limits:
  #  cpu: 200m
  #  memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

applicationYaml:
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty: DEBUG
  spring:
    data:
      redis:
        host: redis-master.tools.svc.cluster.local
        port: 6379
    cloud:
      gateway:
        server:
          webflux:
            routes:
              - id: auditflow_service_route
                uri: http://labs64io-auditflow:8080
                predicates:
                  - Path=/api/v1/audit/**
                filters:
                  - name: RequestRateLimiter
                    args:
                      key-resolver: "#{@ipAddressKeyResolver}"
                      redis-rate-limiter.replenishRate: 1
                      redis-rate-limiter.burstCapacity: 1
                      redis-rate-limiter.requestedTokens: 1

              - id: auditflow_apidocs_route
                uri: http://labs64io-auditflow:8080
                predicates:
                  - Path=/auditflow/v3/api-docs
                filters:
                  - RewritePath=/auditflow/v3/api-docs, /v3/api-docs

              - id: ecommerce_service_route
                uri: http://labs64io-ecommerce:8080
                predicates:
                  - Path=/api/v1/cart/**

              - id: ecommerce_apidocs_route
                uri: http://labs64io-ecommerce:8080
                predicates:
                  - Path=/ecommerce/v3/api-docs
                filters:
                  - RewritePath=/ecommerce/v3/api-docs, /v3/api-docs
  springdoc:
    swagger-ui:
      urls:
        - name: auditflow
          url: http://labs64io-api-gateway.localhost/auditflow/v3/api-docs
        - name: ecommerce
          url: http://labs64io-api-gateway.localhost/ecommerce/v3/api-docs
