image:
  repository: localhost:5005/api-gateway
  tag: latest

service:
  type: ClusterIP

resources:
  #limits:
  #  cpu: 200m
  #  memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

applicationYaml:
  spring:
    cloud:
      gateway:
        server:
          webflux:
            routes:
              - id: auditflow_service_route
                uri: lb://labs64io-auditflow
                predicates:
                  - Path=/api/v1/audit/**
              - id: ecommerce_service_route
                uri: lb://labs64io-ecommerce
                predicates:
                  - Path=/api/v1/cart/**
  springdoc:
    swagger-ui:
      urls:
        - name: auditflow
          url: http://labs64io-auditflow.localhost/v3/api-docs
        - name: ecommerce
          url: http://labs64io-ecommerce.localhost/v3/api-docs
