image:
  repository: localhost:5005/api-gateway
  tag: latest

service:
  type: ClusterIP

resources:
  #limits:
  #  cpu: 200m
  #  memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

applicationYaml:
  application:
    default-broker: rabbit

  spring:
    rabbitmq:
      host: rabbitmq.tools.svc.cluster.local
      port: 5672
      username: labs64
      password: labs64pw
