replicaCount: 1

image:
  repository: localhost:5005/traefik-authproxy
  tag: latest
  pullPolicy: Always

networkPolicy:
  enabled: true

# mock-oauth2-server (just install-tool-mock-oidc)
oidc:
  discoveryUrl: http://mock-oidc.tools.svc.cluster.local:8080/labs64io/.well-known/openid-configuration

logLevel: DEBUG

# Local development overrides for gateway-common
rateLimit:
  average: 100
  burst: 50
