apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  APP_DEFAULT_BROKER: "{{ .Values.application.defaultBroker }}"
  RABBITMQ_HOST: "{{ .Values.application.rabbit.host }}"
  RABBITMQ_PORT: "{{ .Values.application.rabbit.port }}"
  RABBITMQ_USERNAME: "{{ .Values.application.rabbit.username }}"
  AUDIT_TOPIC_NAME: "{{ .Values.application.audit.topicName }}"
  OTLP_ENDPONT: "{{ .Values.application.otel.exporter.otlp.endpoint }}"
