apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-libs.fullname" . }}
  labels:
    {{- include "chart-libs.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.application.rabbitmq.enabled }}
  RABBITMQ_PASSWORD: "{{ .Values.rabbitmq.auth.password }}"
  {{- end }}
