apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_PASSWORD: "{{ .Values.application.rabbit.password }}"
