apiVersion: v2
name: api-gateway
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/Labs64/.github/refs/heads/master/assets/labs64-avatar-128x128.png
type: application
version: 0.1.0
appVersion: "0.0.1"
