apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "chart-libs.fullname" . }}-ratelimit
  labels:
    {{- include "chart-libs.labels" . | nindent 4 }}
spec:
  rateLimit:
    average: 1
    burst: 1
