apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: my-otel-collector
  namespace: default # Or your application's namespace
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 5s
    exporters:
      debug:
        verbosity: detailed # For testing, change to your actual backend exporter (e.g., otlp, jaeger, prometheus)
      # For example, to export to Jaeger:
      # jaeger:
      #   endpoint: "jaeger-collector.jaeger.svc.cluster.local:14250" # Adjust to your Jaeger collector service
      #   tls:
      #     insecure: true # Use this only for development, for production enable TLS
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug] # Or [jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug] # Or [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug] # Or [loki]