mode: deployment
image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  processors:
    batch:
      send_batch_size: 1000
      timeout: 10s
    memory_limiter:
      limit_mib: 256
      spike_limit_mib: 64
    k8sattributes:
      auth_type: "kubeConfig"
      passthrough: false
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.pod.name
          - k8s.container.name
          - k8s.node.name
          - k8s.cluster.name

  exporters:
    jaeger:
      endpoint: "jaeger-collector.observability.svc.cluster.local:14250" # Adjust hostname/port
      tls:
        insecure: true # Use TLS in production!
    debug:
      verbosity: detailed

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [jaeger, debug] # Add other exporters as needed
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [debug] # Add prometheusremotewrite or other metrics exporters
      logs:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [debug] # Add loki or other log exporters
