{{- if .Values.ui.enabled }}
{{- if .Values.ui.application.runtimeEnv.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-libs.fullname" . }}-ui-runtime-env
data:
  env.json: |-
    {{ include "chart-libs.envjson" (dict "env" .Values.ui.application.runtimeEnv.env) | nindent 4 }}
{{- end }}

{{- end }}
