{{- if .Values.ui.enabled }}
{{- if .Values.ui.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart-libs.fullname" . }}-ui-binding
  labels:
    helm.sh/chart: {{ include "chart-libs.chart" . }}
    app.kubernetes.io/name: {{ include "chart-libs.name" . }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: "Labs64.IO"
    app.kubernetes.io/component: ui
subjects:
  - kind: ServiceAccount
    name: {{ include "chart-libs.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "chart-libs.fullname" . }}-ui-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- end }}
