apiVersion: v2
name: chart-libs
type: library
version: 0.0.1
description: A Helm chart for Labs64.IO - Heln Charts Common Templates
icon: https://raw.githubusercontent.com/Labs64/.github/refs/heads/master/assets/labs64-avatar-128x128.png
home: https://labs64.io
keywords:
  - labs64io
  - ecosystem
  - library
sources:
  - https://github.com/Labs64/labs64.io-helm-charts
maintainers:
  - name: labs64
    email: info@labs64.com
