{{- if and .Values.global .Values.global.sharedSecret .Values.global.sharedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.sharedSecret.name | default "labs64io-shared-secret" }}
  labels:
    app.kubernetes.io/name: labs64io-ecosystem
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # Base64 encoded secrets
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.postgresqlPassword | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
{{- end }}
